version: 2

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master


jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:yakkety-curl
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: zz-gijonbus-poc-cache-
      - run:
          name: Docker load if exists
          command: |
            if [ -f caches/zz-gijonbus-poc-docker.tgz ]; then
              zcat caches/zz-gijonbus-poc-docker.tgz | docker load
            fi
      - run:
          name: Build application Docker image
          command: |
            pushd src
            docker build -t ${IMAGE_NAME} .
            popd
            mkdir -p caches
      - run:
          name: Save docker images and histories
          command: |
            docker_images=$(docker images --filter 'dangling=false' \
              --format '{{.Repository}}:{{.Tag}}')
            docker_histories=$(for i in ${docker_images}; \
              do docker history -q $i | grep -v missing; \
            done)
            docker save ${docker_images} ${docker_histories} \
              | gzip > caches/zz-gijonbus-poc-docker.tgz
      - save_cache:
          key: zz-gijonbus-poc-cache-{{ checksum "caches/zz-gijonbus-poc-docker.tgz" }}
          paths:
            - caches/zz-gijonbus-poc-docker.tgz
      - persist_to_workspace:
          root: caches
          paths:
            - zz-gijonbus-poc-docker.tgz

  publish-latest:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: caches
      - setup_remote_docker
      - run:
          name: Load docker images
          command: zcat caches/zz-gijonbus-poc-docker.tgz | docker load
      - run:
          name: Config gcloud
          command: |
            set +o pipefail
            echo $GCP_AUTH | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GCP_PROJECT
      - run:
          name: Tag master
          command: |
            docker tag ${IMAGE_NAME}:latest gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:latest
      - run:
          name: Push latest image to Google Cloud Registry
          command: |
            gcloud auth configure-docker --quiet
            docker push gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:latest

